position:
    type: hector_quadrotor_controllers/PositionController
    x: &pos_xy
        p: 3.0
        i: 1.0
        d: 0.5
        antiwindup: true
        i_clamp: 0.5
        publish_state: true
    y: *pos_xy
    z:
        p: 2.0
        i: 0.0
        d: 0.0
        antiwindup: true
        i_clamp: 2.0
        publish_state: true
    yaw:
        p: 6.0
        i: 2.0
        d: 1.0
        antiwindup: true
        i_clamp: 2.0
        publish_state: true
velocity:
    type: hector_quadrotor_controllers/VelocityController
    x: &vel_xy
        p: 0.3
        i: 0.0
        d: 0.0
        publish_state: true
    y: *vel_xy
    z:
        p: 5.0
        i: 10.0
        d: 0.1
        antiwindup: true
        i_clamp: 2.0
        publish_state: true
attitude:
    type: hector_quadrotor_controllers/AttitudeController
    roll: &rollpitch
        p: 100.0
        i: 0.0
        d: 20.0
        publish_state: true
    pitch: *rollpitch
    yawrate:
        p: 10.0
        i: 0.0
        d: 0.5
        publish_state: true
