path:
- {x:  1.0, y:  0.000, z:  0.0, roll:  0.0, pitch:  0.0, yaw:  0.00}
- {x:  0.5, y: -0.866, z:  0.0, roll:  0.0, pitch:  0.0, yaw:  1.05}
- {x: -0.5, y: -0.866, z:  0.0, roll:  0.0, pitch:  0.0, yaw:  2.09}
- {x: -1.0, y:  0.000, z:  0.0, roll:  0.0, pitch:  0.0, yaw:  3.14}
- {x: -0.5, y:  0.866, z:  0.0, roll:  0.0, pitch:  0.0, yaw: -2.09}
- {x:  0.5, y:  0.866, z:  0.0, roll:  0.0, pitch:  0.0, yaw: -1.05}

clients:
- {name: uav3, pose: 0 }
- {name: uav4, pose: 2 }
- {name: uav5, pose: 4 }

scale: 0.8
base_height: 0.5
repeat: 1
